const vocabularyData = {
    "L": [
        { word: "ola", syllables: ["o", "la"] },
        { word: "Lalo", syllables: ["La", "lo"] },
        { word: "Lola", syllables: ["Lo", "la"] },
        { word: "Alí", syllables: ["A", "lí"] },
        { word: "ala", syllables: ["a", "la"] },
        { word: "aula", syllables: ["au", "la"] },
        { word: "lila", syllables: ["li", "la"] },
        { word: "ele", syllables: ["e", "le"] },
        { word: "lee", syllables: ["le", "e"] }
    ],
    "P": [
        { word: "pie", syllables: ["pie"] },
        { word: "pelo", syllables: ["pe", "lo"] },
        { word: "pipa", syllables: ["pi", "pa"] },
        { word: "pupa", syllables: ["pu", "pa"] },
        { word: "papá", syllables: ["pa", "pá"] },
        { word: "Pepe", syllables: ["Pe", "pe"] },
        { word: "pila", syllables: ["pi", "la"] },
        { word: "pulpo", syllables: ["pul", "po"] },
        { word: "apio", syllables: ["a", "pio"] },
        { word: "palo", syllables: ["pa", "lo"] },
        { word: "papel", syllables: ["pa", "pel"] }
    ],
    "M": [
        { word: "mapa", syllables: ["ma", "pa"] },
        { word: "puma", syllables: ["pu", "ma"] },
        { word: "miel", syllables: ["miel"] },
        { word: "miau", syllables: ["miau"] },
        { word: "momia", syllables: ["mo", "mia"] },
        { word: "pomelo", syllables: ["po", "me", "lo"] },
        { word: "mula", syllables: ["mu", "la"] },
        { word: "malo", syllables: ["ma", "lo"] },
        { word: "lima", syllables: ["li", "ma"] },
        { word: "olmo", syllables: ["ol", "mo"] },
        { word: "mamá", syllables: ["ma", "má"] },
        { word: "muela", syllables: ["mue", "la"] },
        { word: "paloma", syllables: ["pa", "lo", "ma"] },
        { word: "mimo", syllables: ["mi", "mo"] }
    ],
    "S": [
        { word: "sopa", syllables: ["so", "pa"] },
        { word: "sal", syllables: ["sal"] },
        { word: "mesa", syllables: ["me", "sa"] },
        { word: "suela", syllables: ["sue", "la"] },
        { word: "isla", syllables: ["is", "la"] },
        { word: "oso", syllables: ["o", "so"] },
        { word: "salsa", syllables: ["sal", "sa"] },
        { word: "aseo", syllables: ["a", "se", "o"] },
        { word: "suelo", syllables: ["sue", "lo"] },
        { word: "Sol", syllables: ["Sol"] },
        { word: "peso", syllables: ["pe", "so"] },
        { word: "sapo", syllables: ["sa", "po"] },
        { word: "suma", syllables: ["su", "ma"] },
        { word: "Susi", syllables: ["Su", "si"] },
        { word: "pesa", syllables: ["pe", "sa"] },
        { word: "oasis", syllables: ["o", "a", "sis"] },
        { word: "seis", syllables: ["seis"] }
    ],
    "T": [
        { word: "moto", syllables: ["mo", "to"] },
        { word: "tapa", syllables: ["ta", "pa"] },
        { word: "pato", syllables: ["pa", "to"] },
        { word: "auto", syllables: ["au", "to"] },
        { word: "seta", syllables: ["se", "ta"] },
        { word: "pito", syllables: ["pi", "to"] },
        { word: "lata", syllables: ["la", "ta"] },
        { word: "siete", syllables: ["sie", "te"] },
        { word: "potito", syllables: ["po", "ti", "to"] },
        { word: "aleta", syllables: ["a", "le", "ta"] },
        { word: "tela", syllables: ["te", "la"] },
        { word: "palomitas", syllables: ["pa", "lo", "mi", "tas"] },
        { word: "maleta", syllables: ["ma", "le", "ta"] },
        { word: "patatas", syllables: ["pa", "ta", "tas"] },
        { word: "muletas", syllables: ["mu", "le", "tas"] },
        { word: "pelota", syllables: ["pe", "lo", "ta"] },
        { word: "tomate", syllables: ["to", "ma", "te"] },
        { word: "topo", syllables: ["to", "po"] },
        { word: "tila", syllables: ["ti", "la"] },
        { word: "pasta", syllables: ["pas", "ta"] }
    ],
    "N": [
        { word: "lana", syllables: ["la", "na"] },
        { word: "mano", syllables: ["ma", "no"] },
        { word: "uno", syllables: ["u", "no"] },
        { word: "pino", syllables: ["pi", "no"] },
        { word: "Luna", syllables: ["Lu", "na"] },
        { word: "mono", syllables: ["mo", "no"] },
        { word: "peón", syllables: ["pe", "ón"] },
        { word: "león", syllables: ["le", "ón"] },
        { word: "pan", syllables: ["pan"] },
        { word: "melón", syllables: ["me", "lón"] },
        { word: "tapón", syllables: ["ta", "pón"] },
        { word: "piano", syllables: ["pia", "no"] },
        { word: "limón", syllables: ["li", "món"] },
        { word: "puente", syllables: ["puen", "te"] },
        { word: "pimiento", syllables: ["pi", "mien", "to"] },
        { word: "peine", syllables: ["pei", "ne"] },
        { word: "molino", syllables: ["mo", "li", "no"] },
        { word: "atún", syllables: ["a", "tún"] },
        { word: "pantalón", syllables: ["pan", "ta", "lón"] },
        { word: "demonio", syllables: ["de", "mo", "nio"] }
    ],
    "D": [
        { word: "nudo", syllables: ["nu", "do"] },
        { word: "medusa", syllables: ["me", "du", "sa"] },
        { word: "espada", syllables: ["es", "pa", "da"] },
        { word: "diana", syllables: ["dia", "na"] },
        { word: "dedo", syllables: ["de", "do"] },
        { word: "nido", syllables: ["ni", "do"] },
        { word: "diadema", syllables: ["dia", "de", "ma"] },
        { word: "dedal", syllables: ["de", "dal"] },
        { word: "sandía", syllables: ["san", "dí", "a"] },
        { word: "dado", syllables: ["da", "do"] },
        { word: "diamante", syllables: ["dia", "man", "te"] },
        { word: "duende", syllables: ["duen", "de"] },
        { word: "dálmata", syllables: ["dál", "ma", "ta"] },
        { word: "tostada", syllables: ["tos", "ta", "da"] },
        { word: "indio", syllables: ["in", "dio"] },
        { word: "diente", syllables: ["dien", "te"] },
        { word: "toldo", syllables: ["tol", "do"] },
        { word: "monedas", syllables: ["mo", "ne", "das"] },
        { word: "dos", syllables: ["dos"] }
    ],
    "F": [
        { word: "foto", syllables: ["fo", "to"] },
        { word: "estufa", syllables: ["es", "tu", "fa"] },
        { word: "sofá", syllables: ["so", "fá"] },
        { word: "fuente", syllables: ["fuen", "te"] },
        { word: "fantasma", syllables: ["fan", "tas", "ma"] },
        { word: "filete", syllables: ["fi", "le", "te"] },
        { word: "feo", syllables: ["fe", "o"] },
        { word: "mofeta", syllables: ["mo", "fe", "ta"] },
        { word: "falda", syllables: ["fal", "da"] },
        { word: "teléfono", syllables: ["te", "lé", "fo", "no"] },
        { word: "fiesta", syllables: ["fies", "ta"] },
        { word: "fila", syllables: ["fi", "la"] },
        { word: "falta", syllables: ["fal", "ta"] },
        { word: "delfín", syllables: ["del", "fín"] },
        { word: "elefante", syllables: ["e", "le", "fan", "te"] },
        { word: "familia", syllables: ["fa", "mi", "lia"] }
    ],
    "H": [
        { word: "humo", syllables: ["hu", "mo"] },
        { word: "hada", syllables: ["ha", "da"] },
        { word: "hielo", syllables: ["hie", "lo"] },
        { word: "helado", syllables: ["he", "la", "do"] },
        { word: "hiena", syllables: ["hie", "na"] },
        { word: "hola", syllables: ["ho", "la"] },
        { word: "huesos", syllables: ["hue", "sos"] },
        { word: "almohada", syllables: ["al", "mo", "ha", "da"] },
        { word: "hilo", syllables: ["hi", "lo"] },
        { word: "hospital", syllables: ["hos", "pi", "tal"] },
        { word: "hipopótamo", syllables: ["hi", "po", "pó", "ta", "mo"] },
        { word: "hotel", syllables: ["ho", "tel"] }
    ],
    "B": [
        { word: "nube", syllables: ["nu", "be"] },
        { word: "búho", syllables: ["bú", "ho"] },
        { word: "bomba", syllables: ["bom", "ba"] },
        { word: "bufanda", syllables: ["bu", "fan", "da"] },
        { word: "botones", syllables: ["bo", "to", "nes"] },
        { word: "autobús", syllables: ["au", "to", "bús"] },
        { word: "libélula", syllables: ["li", "bé", "lu", "la"] },
        { word: "sabio", syllables: ["sa", "bio"] },
        { word: "bebé", syllables: ["be", "bé"] },
        { word: "abuela", syllables: ["a", "bue", "la"] },
        { word: "batido", syllables: ["ba", "ti", "do"] },
        { word: "botas", syllables: ["bo", "tas"] },
        { word: "balón", syllables: ["ba", "lón"] },
        { word: "bolsa", syllables: ["bol", "sa"] }
    ],
    "V": [
        { word: "uvas", syllables: ["u", "vas"] },
        { word: "vaso", syllables: ["va", "so"] },
        { word: "vela", syllables: ["ve", "la"] },
        { word: "violín", syllables: ["vio", "lín"] },
        { word: "huevos", syllables: ["hue", "vos"] },
        { word: "avioneta", syllables: ["a", "vio", "ne", "ta"] },
        { word: "vestido", syllables: ["ves", "ti", "do"] },
        { word: "avión", syllables: ["a", "vión"] },
        { word: "viento", syllables: ["vien", "to"] },
        { word: "nieve", syllables: ["nie", "ve"] },
        { word: "nueve", syllables: ["nue", "ve"] },
        { word: "ventana", syllables: ["ven", "ta", "na"] },
        { word: "avispa", syllables: ["a", "vis", "pa"] },
        { word: "vino", syllables: ["vi", "no"] },
        { word: "veneno", syllables: ["ve", "ne", "no"] },
        { word: "volante", syllables: ["vo", "lan", "te"] }
    ],
    "C fuerte": [
        { word: "cole", syllables: ["co", "le"] },
        { word: "coco", syllables: ["co", "co"] },
        { word: "cuna", syllables: ["cu", "na"] },
        { word: "cama", syllables: ["ca", "ma"] },
        { word: "casa", syllables: ["ca", "sa"] },
        { word: "copa", syllables: ["co", "pa"] },
        { word: "saco", syllables: ["sa", "co"] },
        { word: "casco", syllables: ["cas", "co"] },
        { word: "cometa", syllables: ["co", "me", "ta"] },
        { word: "canasta", syllables: ["ca", "nas", "ta"] },
        { word: "médico", syllables: ["mé", "di", "co"] },
        { word: "cadena", syllables: ["ca", "de", "na"] },
        { word: "pico", syllables: ["pi", "co"] },
        { word: "camisa", syllables: ["ca", "mi", "sa"] },
        { word: "foca", syllables: ["fo", "ca"] },
        { word: "abanico", syllables: ["a", "ba", "ni", "co"] },
        { word: "camión", syllables: ["ca", "mión"] },
        { word: "candado", syllables: ["can", "da", "do"] },
        { word: "queso", syllables: ["que", "so"] },
        { word: "quiosco", syllables: ["quios", "co"] },
        { word: "esquí", syllables: ["es", "quí"] },
        { word: "mosquito", syllables: ["mos", "qui", "to"] },
        { word: "raqueta", syllables: ["ra", "que", "ta"] },
        { word: "esquimal", syllables: ["es", "qui", "mal"] },
        { word: "esqueleto", syllables: ["es", "que", "le", "to"] },
        { word: "paquete", syllables: ["pa", "que", "te"] },
        { word: "equipo", syllables: ["e", "qui", "po"] },
        { word: "tanque", syllables: ["tan", "que"] },
        { word: "bosque", syllables: ["bos", "que"] },
        { word: "estanque", syllables: ["es", "tan", "que"] },
        { word: "vaca", syllables: ["va", "ca"] }
    ],
    "R fuerte": [
        { word: "rey", syllables: ["rey"] },
        { word: "reina", syllables: ["rei", "na"] },
        { word: "remo", syllables: ["re", "mo"] },
        { word: "barco", syllables: ["bar", "co"] },
        { word: "ratón", syllables: ["ra", "tón"] },
        { word: "rueda", syllables: ["rue", "da"] },
        { word: "tarta", syllables: ["tar", "ta"] },
        { word: "ruleta", syllables: ["ru", "le", "ta"] },
        { word: "radio", syllables: ["ra", "dio"] },
        { word: "rosa", syllables: ["ro", "sa"] },
        { word: "cuaderno", syllables: ["cua", "der", "no"] },
        { word: "risa", syllables: ["ri", "sa"] },
        { word: "perro", syllables: ["pe", "rro"] },
        { word: "marrón", syllables: ["ma", "rrón"] },
        { word: "torre", syllables: ["to", "rre"] },
        { word: "sierra", syllables: ["sie", "rra"] },
        { word: "carrito", syllables: ["ca", "rri", "to"] },
        { word: "turrón", syllables: ["tu", "rrón"] },
        { word: "burro", syllables: ["bu", "rro"] },
        { word: "urraca", syllables: ["u", "rra", "ca"] },
        { word: "carreta", syllables: ["ca", "rre", "ta"] },
        { word: "correo", syllables: ["co", "rre", "o"] },
        { word: "tarro", syllables: ["ta", "rro"] },
        { word: "hierro", syllables: ["hie", "rro"] }
    ],
    "R suave": [
        { word: "pera", syllables: ["pe", "ra"] },
        { word: "lámpara", syllables: ["lám", "pa", "ra"] },
        { word: "loro", syllables: ["lo", "ro"] },
        { word: "caracol", syllables: ["ca", "ra", "col"] },
        { word: "tesoro", syllables: ["te", "so", "ro"] },
        { word: "pirata", syllables: ["pi", "ra", "ta"] },
        { word: "arena", syllables: ["a", "re", "na"] },
        { word: "escalera", syllables: ["es", "ca", "le", "ra"] },
        { word: "caramelos", syllables: ["ca", "ra", "me", "los"] },
        { word: "madera", syllables: ["ma", "de", "ra"] },
        { word: "iris", syllables: ["i", "ris"] },
        { word: "piruleta", syllables: ["pi", "ru", "le", "ta"] },
        { word: "mariposa", syllables: ["ma", "ri", "po", "sa"] },
        { word: "batidora", syllables: ["ba", "ti", "do", "ra"] },
        { word: "dinero", syllables: ["di", "ne", "ro"] },
        { word: "dinosaurio", syllables: ["di", "no", "sau", "rio"] }
    ],
    "G suave": [
        { word: "gato", syllables: ["ga", "to"] },
        { word: "gafas", syllables: ["ga", "fas"] },
        { word: "fuego", syllables: ["fue", "go"] },
        { word: "guantes", syllables: ["guan", "tes"] },
        { word: "goma", syllables: ["go", "ma"] },
        { word: "mago", syllables: ["ma", "go"] },
        { word: "gasolina", syllables: ["ga", "so", "li", "na"] },
        { word: "aguacate", syllables: ["a", "gua", "ca", "te"] },
        { word: "gusano", syllables: ["gu", "sa", "no"] },
        { word: "pegamento", syllables: ["pe", "ga", "men", "to"] },
        { word: "agua", syllables: ["a", "gua"] },
        { word: "gorila", syllables: ["go", "ri", "la"] },
        { word: "paraguas", syllables: ["pa", "ra", "guas"] },
        { word: "guitarra", syllables: ["gui", "ta", "rra"] },
        { word: "águila", syllables: ["á", "gui", "la"] },
        { word: "guepardo", syllables: ["gue", "par", "do"] },
        { word: "espaguetis", syllables: ["es", "pa", "gue", "tis"] },
        { word: "guisantes", syllables: ["gui", "san", "tes"] },
        { word: "paragüero", syllables: ["pa", "ra", "güe", "ro"] },
        { word: "hormiga", syllables: ["hor", "mi", "ga"] },
        { word: "manguera", syllables: ["man", "gue", "ra"] },
        { word: "hamburguesa", syllables: ["ham", "bur", "gue", "sa"] },
        { word: "anguila", syllables: ["an", "gui", "la"] },
        { word: "pingüino", syllables: ["pin", "güi", "no"] },
        { word: "cigüeña", syllables: ["ci", "güe", "ña"] },
        { word: "desagüe", syllables: ["de", "sa", "güe"] },
        { word: "piragua", syllables: ["pi", "ra", "gua"] }
    ],
    "G fuerte": [
        { word: "gel", syllables: ["gel"] },
        { word: "girasol", syllables: ["gi", "ra", "sol"] },
        { word: "colegio", syllables: ["co", "le", "gio"] },
        { word: "ángel", syllables: ["án", "gel"] },
        { word: "página", syllables: ["pá", "gi", "na"] },
        { word: "gigante", syllables: ["gi", "gan", "te"] },
        { word: "gimnasio", syllables: ["gim", "na", "sio"] },
        { word: "genio", syllables: ["ge", "nio"] }
    ],
    "C suave": [
        { word: "zapato", syllables: ["za", "pa", "to"] },
        { word: "zorro", syllables: ["zo", "rro"] },
        { word: "zumo", syllables: ["zu", "mo"] },
        { word: "arroz", syllables: ["a", "rroz"] },
        { word: "calabaza", syllables: ["ca", "la", "ba", "za"] },
        { word: "lazo", syllables: ["la", "zo"] },
        { word: "lápiz", syllables: ["lá", "piz"] },
        { word: "zanahoria", syllables: ["za", "na", "ho", "ria"] },
        { word: "balanza", syllables: ["ba", "lan", "za"] },
        { word: "mazo", syllables: ["ma", "zo"] },
        { word: "peonza", syllables: ["pe", "on", "za"] },
        { word: "nuez", syllables: ["nuez"] },
        { word: "pez", syllables: ["pez"] },
        { word: "manzana", syllables: ["man", "za", "na"] },
        { word: "albornoz", syllables: ["al", "bor", "noz"] },
        { word: "pizarra", syllables: ["pi", "za", "rra"] },
        { word: "zombi", syllables: ["zom", "bi"] },
        { word: "zoo", syllables: ["zo", "o"] },
        { word: "azúcar", syllables: ["a", "zú", "car"] },
        { word: "nariz", syllables: ["na", "riz"] },
        { word: "azul", syllables: ["a", "zul"] },
        { word: "diez", syllables: ["diez"] },
        { word: "pozo", syllables: ["po", "zo"] },
        { word: "cerdo", syllables: ["cer", "do"] },
        { word: "policía", syllables: ["po", "li", "cí", "a"] },
        { word: "cocinero", syllables: ["co", "ci", "ne", "ro"] },
        { word: "pincel", syllables: ["pin", "cel"] },
        { word: "maceta", syllables: ["ma", "ce", "ta"] },
        { word: "cerezas", syllables: ["ce", "re", "zas"] },
        { word: "cereales", syllables: ["ce", "re", "a", "les"] },
        { word: "lince", syllables: ["lin", "ce"] },
        { word: "circo", syllables: ["cir", "co"] },
        { word: "cincuenta", syllables: ["cin", "cuen", "ta"] },
        { word: "aceitunas", syllables: ["a", "cei", "tu", "nas"] }
    ],
    "J": [
        { word: "jirafa", syllables: ["ji", "ra", "fa"] },
        { word: "naranja", syllables: ["na", "ran", "ja"] },
        { word: "tijeras", syllables: ["ti", "je", "ras"] },
        { word: "pájaro", syllables: ["pá", "ja", "ro"] },
        { word: "ojo", syllables: ["o", "jo"] },
        { word: "conejo", syllables: ["co", "ne", "jo"] },
        { word: "juguete", syllables: ["ju", "gue", "te"] },
        { word: "reloj", syllables: ["re", "loj"] },
        { word: "jamón", syllables: ["ja", "món"] },
        { word: "hoja", syllables: ["ho", "ja"] },
        { word: "jaula", syllables: ["jau", "la"] },
        { word: "mujer", syllables: ["mu", "jer"] },
        { word: "oveja", syllables: ["o", "ve", "ja"] },
        { word: "espejo", syllables: ["es", "pe", "jo"] },
        { word: "jarrón", syllables: ["ja", "rrón"] }
    ],
    "Ñ": [
        { word: "araña", syllables: ["a", "ra", "ña"] },
        { word: "albañil", syllables: ["al", "ba", "ñil"] },
        { word: "piña", syllables: ["pi", "ña"] },
        { word: "caña", syllables: ["ca", "ña"] },
        { word: "montaña", syllables: ["mon", "ta", "ña"] },
        { word: "bañera", syllables: ["ba", "ñe", "ra"] },
        { word: "castañas", syllables: ["cas", "ta", "ñas"] },
        { word: "muñeca", syllables: ["mu", "ñe", "ca"] },
        { word: "leña", syllables: ["le", "ña"] },
        { word: "ñandú", syllables: ["ñan", "dú"] },
        { word: "meñique", syllables: ["me", "ñi", "que"] }
    ],
    "CH, X, K, W": [
        { word: "leche", syllables: ["le", "che"] },
        { word: "champú", syllables: ["cham", "pú"] },
        { word: "mapache", syllables: ["ma", "pa", "che"] },
        { word: "mochila", syllables: ["mo", "chi", "la"] },
        { word: "chupete", syllables: ["chu", "pe", "te"] },
        { word: "chuleta", syllables: ["chu", "le", "ta"] },
        { word: "coche", syllables: ["co", "che"] },
        { word: "hucha", syllables: ["hu", "cha"] },
        { word: "hacha", syllables: ["ha", "cha"] },
        { word: "taxi", syllables: ["ta", "xi"] },
        { word: "xilófono", syllables: ["xi", "ló", "fo", "no"] },
        { word: "extintor", syllables: ["ex", "tin", "tor"] },
        { word: "saxofón", syllables: ["sa", "xo", "fón"] },
        { word: "boxeador", syllables: ["bo", "xe", "a", "dor"] },
        { word: "excavadora", syllables: ["ex", "ca", "va", "do", "ra"] },
        { word: "excursión", syllables: ["ex", "cur", "sión"] },
        { word: "koala", syllables: ["ko", "a", "la"] },
        { word: "kétchup", syllables: ["két", "chup"] },
        { word: "vikingo", syllables: ["vi", "kin", "go"] },
        { word: "kárate", syllables: ["ká", "ra", "te"] },
        { word: "kiwi", syllables: ["ki", "wi"] },
        { word: "wifi", syllables: ["wi", "fi"] },
        { word: "waterpolo", syllables: ["wa", "ter", "po", "lo"] },
        { word: "sándwich", syllables: ["sán", "dwich"] },
        { word: "windsurf", syllables: ["wind", "surf"] }
    ]
};
